# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### 上传文件接口
POST http://localhost:9501/api/upload/file?a=12
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="tmp.mp4"

< /Users/idcpj/Web/easyswoole/Doc/tmp.mp4
--WebAppBoundary--

### 文件信息上传
POST http://localhost:9501/api/video/add
Content-Type: application/x-www-form-urlencoded

name=cpj&image=11&url=asdsadas&content=conent_asdasd&cat_id=1123&type=1

### elasticsearch 聚合查询

## 添加数据
curl -X POST -H 'Content-Type: application/json' http://127.0.0.1:9200/video1/video/ -d'
{
"name":"aaa",
"id":
}
'


#查询数据
curl -X GET -H 'Content-Type: application/json' http://127.0.0.1:9200/video1/video/_search -d'
{
"size":0,
 "aggs":{
    "xin_name":{
      "terms":{
        "field":"cat_id"
      }
    }
 }
}
'